version: "3"

services:

  commonshare:
    build: .
    image: commonfare/commonshare-python
    container_name: commonshare
    volumes:
     - ./data:/usr/src/app/data
    ports:
      - "5000:5000"
    # Uncomment environment section to use different values
    # environment:
      # - TASK=parse
      # - GEXF_INPUT=./data/input/latest.gexf
      # - PAGERANK_FILE=./data/output/recommenderdata.gexf
